### PR TITLE
Modified Links and Updated ReadMe

### PR DESCRIPTION
**Pull request by Cioraz**
Changes to the Links and Readme. #100

### CODE REVIEW

**Comment by LeeWannacott** [comment]
Looks good; the new minified links aren't minified there is also https://github.com/LeeWannacott/table-sort-js/blob/master/public/docs/html5.html#LL71C1-L71C1 . Which is this page: https://leewannacott.github.io/table-sort-js/docs/html5.html

**Comment by LeeWannacott** [comment]
Hey, After thinking about this more I don't think we need to do @1 we could just do https://cdn.jsdelivr.net/npm/table-sort-js/table-sort.js and https://cdn.jsdelivr.net/npm/table-sort-js/table-sort.min.js for the minified version; I think this is less confusing. @Cioraz Sorry for the inconvenience; would you be able to change the links to these instead?

**Comment by Cioraz** [comment]
Sure I'll change them

**Comment by LeeWannacott** [comment]
@Cioraz This latest commit looks good, the second commit is changing a bunch of stuff that doesn't need to be changed. You could run `git revert 36f97c957d2dc90d1ce9cbf17519ca559f7f3617` to undo the second commit. This will make a new commit thats reverts the second commit and then you would push this revert commit to the branch and it should get rid of the unnecessary changes in the second commit.

**Comment by Cioraz** [comment]
Hey, im running into a few errors doing what you stated above. Could I create another pull request with only these changes ?

**Comment by LeeWannacott** [comment]
> Hey, im running into a few errors doing what you stated above. Could I create another pull request with only these changes ?

Sure.

**Comment by LeeWannacott** [comment]
Done in PR https://github.com/LeeWannacott/table-sort-js/pull/107

**Pull request closed without merging**
