### PR TITLE
Add support for "disable-sort" class per column

### LINKED ISSUE #7: Add a tag class for disabling sort on specific table columns.
The user might not want all columns to sort when clicked allow them to disable specific columns with a class such as: disable-sort.

### PR DESCRIPTION
**Pull request by vhtkrk**
Resolves #7. And maybe #51 too but I'm not 100% sure if that's what they asked for.

### CODE REVIEW

**Comment by LeeWannacott** [comment]
Hey @vhtkrk 

In #51 they are talking about excluding rows from being sorted; whereas this is disabling the sort on the click of columns.

I'm wondering whether this feature should also freeze the column in place, another-words if the user clicks on another column the column that has `disable-sort` on it should remain in place/ in the original order. Because I can't think of a use case where you would want to disable sorting on the click of a column and yet want it to be sorted when clicking on another column; unless you can? :thinking: 

However, it may be a bit tricky to implement considering table-sort-js sorts the `<tr>`.

What are your thoughts? are you up for trying to implement this? :thinking: 

Thanks.

**Comment by LeeWannacott** [comment]
Hmmmm, maybe there is a use case where if a user clicks on a column and it doesn't sort properly; so you want to disable it. Maybe the freezing a column should be a different class. Could you add documentation for `disable-sort` to LeeWannacott/table-sort-js/blob/master/public/docs/classes.html and LeeWannacott/table-sort-js/blob/master/README.md and I'm happy to merge the feature. Thanks :+1:

**Comment by vhtkrk** [comment]
Thanks for your input. 

I actually have a use case for just what I made: I have a bunch of rows where there's either "First name" and "Last name" as separate fields, or just a "Name" field that has both in it. The easiest way to fit in with other requirements was to stuff it into a table with 2 columns: "Name" and another one with an empty heading. Then in a loop I either put the full name in the first column or the first name in the first column and last name in the second. But sorting by that second field was confusing, especially when the column header has no text.

I'll have to see what it would take to freeze the columns so they won't be sorted at all, but that sounds like it's a bit more work than this, so no promises as I don't have immediate use for it myself. But I agree it should be a different feature from this one.

I'll update the docs tomorrow or Sunday if I don't find the time tomorrow.

**Comment by LeeWannacott** [comment]
> I actually have a use case for just what I made

OK cool; I never thought of that use case.

> I'll have to see what it would take to freeze the columns

Yeah, I wouldn't worry about freezing the column for this PR; can do that as a separate feature.

> I'll update the docs tomorrow or Sunday if I don't find the time tomorrow.

All good, just whenever is convenient :+1:

**Comment by vhtkrk** [comment]
I've updated the documentation. Also added missing `remember-sort` documentation to `public/docs/classes.html` and fixed a few typos while I was at it.

**Comment by LeeWannacott** [comment]
> I've updated the documentation. Also added missing remember-sort documentation to public/docs/classes.html and fixed a few typos while I was at it.

Looks good to me!

Merged in commit: c8d4273ecf8a9b4f0948ab0abac1cb945cbc3d8e

**Pull request merged**
