### PR TITLE
fix: handling negative and decimal numeric cases #63 and #64

### PR DESCRIPTION
**Pull request by scodes73**
Fixes issues mentioned in #63 #64

P.S. nit: used `numeric-sort` instead of `numbers-sort` ( Lemme know if you want that to be changed)

### CODE REVIEW

**Comment by LeeWannacott** [comment]
Looks good to me for the most part. I think negative numbers can also be displayed using '(' ')' pretty common in financial stuff.

We could handle currency in a separate PR; which could most likely use the same sorting function just with the currency sign ($ etc) stripped.

**Comment by scodes73** [comment]
@LeeWannacott Can you give me some examples of those notation '(' ')' , so I can adjust regex.
Also good eye 👀, I did not check for empty case and some other alphabet case, then it's gonna mess up the order, we could only apply numeric-sort only if it matches all elements now just threshold, what do you think?

I will update readme once everything is finalised.✅

**Comment by LeeWannacott** [comment]
> @LeeWannacott Can you give me some examples of those notation '(' ')' , so I can adjust regex. Also good eye eyes, I did not check for empty case and some other alphabet case, then it's gonna mess up the order, we could only apply numeric-sort only if it matches all elements now just threshold, what do you think?

I think you could do maybe 66%-80% , but I don't like a 100% threshold I think that might be a bit too strict. Or just leave it as is and find out a way to check if its numeric-sort and doesn't return NaN or something then let it go to the else below:
``` javascript
 } else{
          return a.localeCompare(
            b,
            navigator.languages[0] || navigator.language,
```
Although this might be buggy.. I'd maybe write some tests and see what happens if its a string of words and what happens might inform you on how to handle it; whether is returns NaN (you could do [isNaN())](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN) or not. You might not have to handle it at all :shrug: 

The '( ')' is just another way to do '-' except you put them around numbers to signify its a negative which would look like e.g `(10)` or might have $ sign in it or around it ($10). I think its commonly used in financial statements for the most part.
https://ux.stackexchange.com/questions/1869/preferred-format-to-display-negative-currency-us-english

Empty cases should be okay in theory because it will do the fillValue thing.

``` javascript
 if (a.includes(`${fillValue}#`)) {
          return 1;
        } else if (b.includes(`${fillValue}#`)) {
          return -1;
}
```

> 
> I will update readme once everything is finalised.white_check_mark

Sweet.

**Comment by scodes73** [comment]
Hey @LeeWannacott  can you check up both code and testcases, if everything seems fine, I'll get on with readme.

**Comment by LeeWannacott** [comment]
> @LeeWannacott
> 
>     * Refactored to multiple functions
> 
>     * Reduced no. of testcases
> 
>     * README updated
> 
> 
> (Let me know of any changes to be done)
> 
> > We should handle currency but can always do that later in separate PR
> 
> Separate PR for currency is better.

@scodes73  Sweet!

Do we need to have parseNumberFromString, strLocaleCompare, handleNumbers functions declared within sortAscending? that means they will be defined every time someone is sorting a column which doesn't sound ideal.


` Decimals (can also be used for Semantic Versioning)` I don't think we need this in the readme as its not related to this class; table-sort-js can handle semantic versioning by default (I think).

**Comment by LeeWannacott** [comment]
@scodes73 Looks good to me! . Ready to merge? I'll probably do a release tomorrow its pretty late.

**Pull request merged**
